### ISSUE TITLE
Why we need fix Pad Size when training with SyncBatchNorm?

### ISSUE THREAD

**Issue by kohillyang** [HRNet/HRNet-FCOS#6]
The readme.md says we need to fix the image padding size when using SyncBN. But Since the process of calculating SyncBatchNorm is independent with the size of the image. And not fixing the padding size can speed the training up.
Does it because not fixing them will influence the last mAP?
Thanks a lot.

**Comment by bearcatt** [comment]
yes, as mentioned [here](https://github.com/HRNet/HRNet-FCOS/blob/master/maskrcnn_benchmark/structures/image_list.py#L62), fix padding size will improve the performance.

**Comment by kohillyang** [comment]
Got it, thank you very much.
